# Generated by Django 5.0.1 on 2024-01-03 21:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('link', models.CharField(max_length=1000)),
                ('new', models.CharField(max_length=6)),
                ('uid', models.UUIDField(default=uuid.UUID('e30f3bc1-e133-432e-861d-d08629b4b366'), primary_key=True, serialize=False)),
            ],
        ),
    ]
